import { Router } from "express";
import { authRouter } from "./auth/router";
import { onboardingRouter } from "./onboardings/router";
import { goalRouter } from "./goals/router";
import { accountRouter } from "./accounts/router";
import { settingRouter } from "./settings/router";
import { transactionRouter } from "./transactions/router";
import { budgetRouter } from "./budgets/router";
import { currencyRouter } from "./currencies/router";
import { goalTypeRouter } from "./goal_types/router";
import { userRouter } from "./users/router";
import { analyticsRouter } from "./analytics/router";
import { categoryRouter } from "./categories/router";
import { transactionTypeRouter } from "./transaction_types/router";
import { stateRouter } from "./states/router";

export const router: Router = Router();
router.use("/auth", authRouter);
router.use("/onboardings", onboardingRouter);
router.use("/goals", goalRouter);
router.use("/accounts", accountRouter);
router.use("/settings", settingRouter);
router.use("/transactions", transactionRouter);
router.use("/budgets", budgetRouter);
router.use("/currencies", currencyRouter);
router.use("/goal-types", goalTypeRouter);
router.use("/users", userRouter);
router.use("/analytics", analyticsRouter);
router.use("/categories", categoryRouter);
router.use("/transaction-types", transactionTypeRouter);
router.use("/states", stateRouter);
